name: PostgreSQL Data Accessor CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --ignore-scripts
    
    - name: Run linting
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    - name: Generate coverage report
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci --ignore-scripts
    
    - name: Build package
      run: npm run build
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Get latest version from npm
      id: get-latest
      run: |
        LATEST_VERSION=$(npm view postgresql-data-accessor version)
        echo "Latest version on npm: $LATEST_VERSION"
        echo "latest=$LATEST_VERSION" >> $GITHUB_OUTPUT
    
    - name: Bump patch version from latest
      run: |
        LATEST_VERSION=${{ steps.get-latest.outputs.latest }}
        echo "Bumping from latest version: $LATEST_VERSION"
        
        # Extract major.minor.patch components
        IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        
        echo "New version will be: $NEW_VERSION"
        echo "::notice::Bumping from $LATEST_VERSION to $NEW_VERSION"
        
        # Update package.json version
        npm version $NEW_VERSION --no-git-tag-version
        
        # Verify the version was updated
        ACTUAL_VERSION=$(node -p "require('./package.json').version")
        echo "Package.json now shows version: $ACTUAL_VERSION"
        
        # Store the new version for later use
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
    
    - name: Get new version
      id: get-version
      run: |
        NEW_VERSION=${{ env.NEW_VERSION }}
        echo "New version: $NEW_VERSION"
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
    
    - name: Check if version exists on npm
      id: check-version
      run: |
        NEW_VERSION=${{ steps.get-version.outputs.version }}
        echo "Checking if version $NEW_VERSION exists on npm..."
        
        # Use npm view with explicit error handling
        if npm view postgresql-data-accessor@$NEW_VERSION > /dev/null 2>&1; then
          echo "Version $NEW_VERSION already exists on npm"
          echo "should_publish=false" >> $GITHUB_OUTPUT
          echo "::warning::Version $NEW_VERSION already exists on npm, skipping publish"
        else
          echo "Version $NEW_VERSION does not exist on npm"
          echo "should_publish=true" >> $GITHUB_OUTPUT
          echo "::notice::Version $NEW_VERSION is new, will publish"
        fi
    
    - name: Publish to NPM
      if: steps.check-version.outputs.should_publish == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Skip publishing
      if: steps.check-version.outputs.should_publish == 'false'
      run: echo "Skipping publish - version ${{ steps.get-version.outputs.version }} already exists on npm"
    
    - name: Create Git tag
      if: steps.check-version.outputs.should_publish == 'true'
      run: |
        git tag v${{ steps.get-version.outputs.version }}
        git push origin v${{ steps.get-version.outputs.version }}
    
    - name: Push version bump
      if: steps.check-version.outputs.should_publish == 'true'
      run: |
        git add package.json package-lock.json
        git commit -m "Bump version to ${{ steps.get-version.outputs.version }}"
        git push origin master
    
    - name: Skip Git operations
      if: steps.check-version.outputs.should_publish == 'false'
      run: echo "Skipping Git operations - version already exists"
