name: GitHub Release Only

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the current version from package.json
          VERSION=$(node -p "require('./package.json').version")
          
          # Check if tag already exists
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists, skipping tag creation"
          else
            # Create and push the tag
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            # Create annotated tag
            git tag -a "v$VERSION" -m "Release v$VERSION"
            
            # Push the tag
            git push origin "v$VERSION"
          fi
          
          # Create GitHub release if it doesn't exist
          if ! gh release view "v$VERSION" >/dev/null 2>&1; then
            gh release create "v$VERSION" \
              --title "Release v$VERSION" \
              --notes "Release v$VERSION of easy-postgresql-accessor package" \
              --target master
          else
            echo "GitHub release v$VERSION already exists"
          fi
