name: Initial Release v0.0.1

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '0.0.1'
        type: string

jobs:
  initial-release:
    name: Initial Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: production
        run: |
          # Create and push the initial release tag
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create annotated tag
          git tag -a v${{ github.event.inputs.version }} -m "Initial release v${{ github.event.inputs.version }}"
          
          # Push the tag
          git push origin v${{ github.event.inputs.version }}
          
          # Create GitHub release
          gh release create v${{ github.event.inputs.version }} \
            --title "Release v${{ github.event.inputs.version }}" \
            --notes "Initial release of easy-postgresql-accessor package" \
            --target master
